### ISSUE TITLE
'Latex' directory is incoherent

### ISSUE THREAD

**Issue by sylph1o** [texstremists/Document-design#4]
My issue against the existence of this directory is twofold.
1. There is LaTeX-related content outside of it. Furthermore, almost all (if not all) the current content of this repository is LaTeX-related and therefore should be inside this directory. A directory that sits alone at the top level of a repository sounds useless to me.
2. The stance taken elsewhere in this repository seems to be to focus on the intended production (article, bibliography, drawing, etc.), not on the software used to achieve it. This side of the issue applies to the 'Beamer' directory as well, which should perhaps be discussed in a separate.

Do you agree or disagree, and why ? Any solution to propose ?

Edit: typo

**Comment by sylph1o** [comment]
I surmise that this directory was created to place files which fit in no other existing directory; it seems to be the current use, in any case. I agree that we need such directory, for at least two reasons:
- no one wants a mess of files at the top level, and
- it would be ludicrous to create a new category every time a new file is pushed (some global perspective is required).

Consequently, I propose to rename 'Latex' according to its function; e.g. 'unsorted' or 'miscellaneous'.

**Comment by neerby** [comment]
I tend to strongly agree with that. I've got nothing to argue with except the initial purpose which, as you mention, doesn't matter anyway.

I would be in favour of redesigning the directory structure based on purpose and not means.
With the code we got so far, there's no way we can come up with an accurate and persistent hierarchy: we must accept to let it grow and change/rename it in the future, maybe repeatedly.
In addition, it lightens the burden of choosing a directory for new contributors.

Therefore I'm all up for turning `Latex` into `unsorted`, then taking time to shape the repository.
In order to enforce coherence with these ideas, we could also rename `Beamer` as `presentations`

**Comment by sylph1o** [comment]
I agree with the renaming of 'Beamer' into 'presentations'.

**Comment by CsatiZoltan** [comment]
I think `Latex` was one of the earliest folder created. At that time we did not have such organizing principles available. I agree renaming it and also `Beamer`. Any of you can do it. I am curious what will happen to the git log.

**Comment by sylph1o** [comment]
Enforced in 8988870197fe74b6fca001e95f8f1af0498dc489.

**Comment by CsatiZoltan** [comment]
@sylph1o  Please note that the previous directories are not removed. I.e. you copied instead of moving. Also, the main README file should then contain the appropriate section titles and links.

**Comment by sylph1o** [comment]
You are right. I am very surprised, because I *did* move the directories, and my local repository was correct. I must have been careless when I staged files for commit, and forgot to add the removed files.

Fixed in b898b8c.
